spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
broker:
  rabbitmq:
    exchange: sofka.exchange
    queue: sofka.queue
    routingKey: sofka.routingKey
